version: '3.7'

services:
  spring-data-jpa-docker:
    image: 'spring-data-jpa-docker:latest'
    build:
      context: .
    container_name: spring-data-jpa-docker
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springjpadocker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql