version: '3.7'

services:
  db:
    image: 'postgres:alpine'
    container_name: db
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql


  spring-data-jpa-docker:
    image: 'spring-data-jpa-docker:latest'
    container_name: spring-data-jpa-docker
    ports:
      - '5432:5432'
    depends_on:
      - db
    # build the docker file of this container
    # context: . =>  Dockerfile file should be existing in the current directory (in the same folder of the docker-compose.yml file)
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springjpadocker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create